### ISSUE TITLE
Error in server run

### ISSUE THREAD

**Issue by Vladymyrlem** [mohammadrony/e-store#1]
Hello/ After run server with command "start", i have error "Unknown command: "src/app.js"" and string  [nodemon] app crashed - waiting for file changes before starting... Do you know what is this and what i must to do for run server?

**Comment by mohammadrony** [comment]
I don't understand how this error occurred. There might be a dependency problem facing on your computer. Please try to update those dependency. If still this problem occurs try to create a new project from beginning then copy this codes in your project one by one.
