### ISSUE TITLE
Adding product

### ISSUE THREAD

**Issue by Kesavan-Hex** [mohammadrony/e-store#3]
How to add product with admin panel

**Comment by mohammadrony** [comment]
You can check those data from `server/seed/*.json` files. In `server/seed/users.json` file user model is specified. In user model **Admin** is specified by **priority: 1**. And Customer user is specified by priority 2. Change the email if you need to or any other field also.

**Important**
Remember that priority 1's userType should be "Admin" and priority 2's userType should be "Customer".

You need to feed the database those data using this command.
```
cd server && npm run seed
```

After feeding those data you need to login with that user email and password from the [login page](http://localhost:8080/login). Then when you go to these page
http://localhost:8080/products
or
localhost:8080/products/:category
localhost:8080/products/:category/:sub-category
localhost:8080/products/:category/:sub-category/:sub-sub-category

 you will see a `Add Product` or `Add Item` button in product navbar to add a new product..

When you get there you will see different fields about a product.
You can add Product title, price, category (also you can create category there), overview in html text, description in html text and maximum 10 images of the product. Then when you submit this form you will see the product is added into that category. And that product is going to be seen by anyone.

Hope this clears the process of adding a new product.

**Comment by Kesavan-Hex** [comment]
Thank you it worked
