### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]:

### ISSUE THREAD

**Issue by Ahmedbm99** [mohammadrony/e-store#7]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client  
in the login , registre

**Comment by Kesavan-Hex** [comment]
share full log not enough information


and login and register working

**Comment by mohammadrony** [comment]
This issue may arise during the process of creating a response object for frontend. If you encounter this error again, please share the steps to reproduce it.
