### ISSUE TITLE
Product details

### ISSUE THREAD

**Issue by Ahmedbm99** [mohammadrony/e-store#8]
There is an error of fetching data to show product details

**Comment by mohammadrony** [comment]
Could you please provide more information on what error is showing up?

**Comment by Ahmedbm99** [comment]
When i want view product details, there is an error in console says “ An
error occured when trying to fetch the products.”

**Comment by mohammadrony** [comment]
When a URL is accessed from the browser, it generates a log in the backend terminal containing relevant error about the request. Please share that in here.

**Comment by Ahmedbm99** [comment]
Properties does not exist on type any[]

**Comment by mohammadrony** [comment]
Can you give some screenshots of the error and the website so that I can understand more better.

**Comment by mohammadrony** [comment]
Also provide backend error log.

**Comment by Ahmedbm99** [comment]
[image: image.png][image: image.png]
i changed shop to supermarket

**Comment by mohammadrony** [comment]
Image is not visible. Please use Github UI for better response.

**Comment by Ahmedbm99** [comment]
![image](https://github.com/mohammadrony/emarket/assets/101886914/fa8af14f-0c6a-478e-89e7-3fe0800e09c5)![image](https://github.com/mohammadrony/emarket/assets/101886914/ceabb614-c327-4186-a96f-42c47d430c95)
![Uploading 241784099...]

**Comment by mohammadrony** [comment]
When you change directory name you may also need to change the shop keyword used in the root directory of the project. Like `jsconfig.json` file and `vetur.config.js` file also inside any file where `shop` could be used as a directory name.

**Comment by Ahmedbm99** [comment]
I did changed it

**Comment by mohammadrony** [comment]
Did you check if this error appears before changing directory name?

**Comment by Ahmedbm99** [comment]
The problem was in server,
Method getproduct must have returned attributes

**Comment by Ahmedbm99** [comment]
Btw can u help me to add chart component in product details? Showing price history

**Comment by mohammadrony** [comment]
Sorry, I cannot be able to do so. Now I have very less time to work in this project. But you can follow some other repository or tutorials for it.

**Comment by Ahmedbm99** [comment]
Ok, I will try. Thank u
